spring:
  application:
    name: process-data-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlite:${SQLITE_DATABASE_PATH:data/desafio.sqlite}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-init-sql: "PRAGMA query_only = ON"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
  info:
    app:
      enabled: true

info:
  app:
    name: process-data-service
    description: API REST somente leitura para dados processuais do TJSC
    version: 0.0.1-SNAPSHOT

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    br.jus.tjsc.ai.process: DEBUG
    org.springframework.jdbc: WARN
