export enum TipoDocumento {
  Despacho                       = 'Despacho',
  Certidao                       = 'Certidão',
  PeticaoInicial                 = 'Petição Inicial',
  AtaDeAudiencia                 = 'Ata de Audiência',
  Contestacao                    = 'Contestação',
  Sentenca                       = 'Sentença',
  Replica                        = 'Réplica',
  DecisaoDeSaneamento            = 'Decisão de Saneamento',
  DecisaoInterlocutoria          = 'Decisão Interlocutória',
  ManifestacaoSobreProvas        = 'Manifestação sobre Provas',
  PeticaoDeAcordo                = 'Petição de Acordo',
  SentencaHomologatoria          = 'Sentença Homologatória de Acordo',
  ParecerDoMinisterioPublico     = 'Parecer do Ministério Público',
  ExcecaoDePreExecutividade      = 'Exceção de Pré-Executividade',
  EmendaAInicial                 = 'Emenda à Inicial',
  EmbargosAExecucaoFiscal        = 'Embargos à Execução Fiscal',
  EmbargosDeDeclaracao           = 'Embargos de Declaração',
  Apelacao                       = 'Apelação',
  ContrarrazoesDeApelacao        = 'Contrarrazões de Apelação',
}
