FROM eclipse-temurin:25-jdk AS build
WORKDIR /app
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline -q
COPY src/ src/
RUN ./mvnw package -DskipTests -q

FROM eclipse-temurin:25-jre
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/target/process-data-service-0.0.1-SNAPSHOT.jar app.jar
COPY data/desafio.sqlite data/desafio.sqlite
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
